# Generated by Django 3.2 on 2021-07-28 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='high_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='low_price',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='new_product',
            field=models.BooleanField(default=False),
        ),
    ]
