# Generated by Django 3.2 on 2021-07-28 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0006_product_productorder_subscriber_usercontact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productorder',
            name='product',
        ),
        migrations.RemoveField(
            model_name='productorder',
            name='user',
        ),
        migrations.DeleteModel(
            name='Subscriber',
        ),
        migrations.DeleteModel(
            name='UserContact',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='ProductOrder',
        ),
    ]
