# Generated by Django 3.2 on 2021-07-28 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0008_product_productorder_subscriber_usercontact'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='featured_tag',
            field=models.BooleanField(default=True, help_text='Check this field if you want this product to be in the featured list'),
        ),
    ]
