# Generated by Django 3.2 on 2021-07-29 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoppapp', '0009_product_featured_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='high_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='low_price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='new_product',
        ),
    ]
